title: simple64
description: An easy to use N64 emulator. Available for Windows and Linux
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
download_url: https://github.com/simple64/simple64/releases
